server:
  port: 9001
spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: people-grp-0
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      bootstrap-servers: localhost:9092
      acks: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
kafka:
  topics:
    people:
      name: people
      partitions: 1
      replication-factor: 1

kafka-topics:
  - fake-topic1
  - fake-topic2

kafka-api:
  topics:
    mytopic1:
      name: my-topic1
    mytopic2:
      name: my-topic2
